stages:
  data_cleaning:
    cmd: uv run src/main.py -p clean
    deps:
    - data/Estudios_Economicos_Consolidado.xlsx
    - src/data_cleaner.py
    - src/main.py
    outs:
    - data/dataset_cleaned.xlsx
  data_transformation:
    cmd: uv run src/main.py -p transform
    deps:
    - data/dataset_cleaned.xlsx
    - src/data_transformer.py
    - src/main.py
